## docker-compose.yml
version: '3.7'
services:
  postgres:
    image: postgres:15
    command:
      [
        "-c",
        "ssl=on",
        "-c",
        "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem",
        "-c",
        "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
      ]
    ports:
      - 35432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data15:/var/lib/postgresql/data/
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  app:
    image: app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    build:
      context: .
      network: host
    environment:
      DEBUG: 1
      ENVIRONMENT: local
      PYTHONBREAKPOINT: ipdb.set_trace
    volumes:
      - ./app:/app
    ports:
      - 8001:8000
    depends_on:
      - postgres

volumes:
  postgres_data15:
  redis_data:
